apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemotodoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksdemotodoapp
  template:
    metadata:
      labels:
        app: aksdemotodoapp
    spec:
      containers:
      - name: aksdemotodoapp
        image: <your-acr-name>.azurecr.io/aksdemotodoapp:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aksdemotodoapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aksdemotodoapp
